# Generated by Django 2.1.3 on 2018-11-20 08:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181120_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='subheading',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
