# Generated by Django 2.1.3 on 2018-11-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_subheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='subheading',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
