# Generated by Django 2.1.3 on 2018-11-20 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20181120_1143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='IndexPage',
        ),
    ]
