# Generated by Django 2.1.3 on 2018-11-20 10:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0006_auto_20181120_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('project_title', models.CharField(blank=True, max_length=140)),
                ('subheading', models.CharField(blank=True, max_length=140)),
                ('date', models.DateField(verbose_name='Post date')),
                ('clientname', models.CharField(max_length=250)),
                ('body', wagtail.core.fields.RichTextField()),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
