# Generated by Django 2.1.3 on 2018-11-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_projectpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='project_title',
        ),
    ]
